### ISSUE TITLE
Unable to save creds, plugin causes Volumio to restart.

### ISSUE THREAD

**Issue by nvqna** [Saiyato/volumio-lastfm-plugin#22]
I've installed the plugin according to instructions provided in [Issue 19](https://github.com/Saiyato/volumio-lastfm-plugin/issues/19#issuecomment-1002618076):

```
    sudo wget -O volumio_install_from_zip.sh https://raw.githubusercontent.com/Saiyato/volumio-plugin-helper/master/volumio_install_from_zip.sh && sudo chmod +x volumio_install_from_zip.sh
    ./volumio_install_from_zip.sh Saiyato volumio-lastfm-plugin
```

I've noticed a couple of issues.

1. Can't save config

On the config screen for the plugin, when I enter the API key etc and click 'Save', nothing happens. 

```
volumio@volumio:~$ sudo journalctl -f
Jan 28 20:22:41 volumio sudo[1751]:  volumio : TTY=pts/0 ; PWD=/home/volumio ; USER=root ; COMMAND=/bin/journalctl -f
Jan 28 20:22:41 volumio sudo[1751]: pam_unix(sudo:session): session opened for user root by volumio(uid=0)
Jan 28 20:22:47 volumio volumio[768]: info: CALLMETHOD: miscellanea lastfm updateCredentials [object Object]
Jan 28 20:22:47 volumio volumio[768]: info: CoreCommandRouter::executeOnPlugin: lastfm , updateCredentials
Jan 28 20:22:52 volumio volumio[768]: info: CoreCommandRouter::executeOnPlugin: my_volumio , getMyVolumioStatus
Jan 28 20:22:52 volumio volumio[768]: info: CoreCommandRouter::executeOnPlugin: my_volumio , getMyVolumioToken
Jan 28 20:22:55 volumio volumio[768]: info: CoreCommandRouter::getUIConfigOnPlugin
Jan 28 20:22:55 volumio volumio[768]: info: Loaded the previous config.
Jan 28 20:22:55 volumio volumio[768]: info: ## populating UI...
Jan 28 20:22:55 volumio volumio[768]: info: 1/3 settings loaded
Jan 28 20:22:55 volumio volumio[768]: info: 2/3 settings loaded
Jan 28 20:22:55 volumio volumio[768]: info: 3/3 settings loaded
Jan 28 20:22:55 volumio volumio[768]: info: Populated config screen.
Jan 28 20:23:22 volumio volumio[768]: error: error
Jan 28 20:23:22 volumio volumio[768]: error: error
Jan 28 20:23:22 volumio volumio[768]: error: error
Jan 28 20:23:22 volumio volumio[768]: error: error
Jan 28 20:23:23 volumio volumio[768]: info: CALLMETHOD: miscellanea lastfm updateCredentials [object Object]
Jan 28 20:23:23 volumio volumio[768]: info: CoreCommandRouter::executeOnPlugin: lastfm , updateCredentials
Jan 28 20:23:28 volumio volumio[768]: info: CALLMETHOD: miscellanea lastfm updateDebugSettings [object Object]
Jan 28 20:23:28 volumio volumio[768]: info: CoreCommandRouter::executeOnPlugin: lastfm , updateDebugSettings
Jan 28 20:23:29 volumio volumio[768]: info: CALLMETHOD: miscellanea lastfm updateDebugSettings [object Object]
Jan 28 20:23:29 volumio volumio[768]: info: CoreCommandRouter::executeOnPlugin: lastfm , updateDebugSettings
```

When I leave the config page in the UI and go back to it, the settings are gone.

I then tried to manually add the API creds in `/data/plugins/user_interface/lastfm/config.json`. After adding them here and rebooting the RPi, the settings page for the plugin remains empty.

EDIT: If I manually add the API creds in /data/configuration/user_interface/lastfm/config.json, they appear in the UI. However, I still cannot edit them via the UI - nothing happens when I click save. With the creds in config.json, the issue below still occurs.

2. Volumio restarts when a track is played
When I play a track, I get about six seconds of audio and Volumio restarts.

Log output:

```
Jan 28 22:12:15 volumio volumio[768]: info: CorePlayQueue::getTrack 0
Jan 28 22:12:15 volumio volumio[768]: verbose: STATE SERVICE {"status":"play","position":0,"seek":445,"duration":180,"samplerate":"44.1 kHz","bitdepth":"24 bit","channels":2,"random":false,"updatedb":false,"repeat":false,"bitrate":"320 Kbps","isStreaming":false,"title":"Intended Simply","artist":"PKNN","album":"The Heat","uri":"NAS/fatboy/PKNN/The Heat/01 Intended Simply.mp3","trackType":"mp3"}
Jan 28 22:12:15 volumio volumio[768]: verbose: CURRENT POSITION 0
Jan 28 22:12:15 volumio volumio[768]: info: CoreStateMachine::syncState   stateService play
Jan 28 22:12:15 volumio volumio[768]: info: CoreStateMachine::syncState   currentStatus play
Jan 28 22:12:15 volumio volumio[768]: info: Received an update from plugin. extracting info from payload
Jan 28 22:12:15 volumio volumio[768]: info: CoreStateMachine::pushState
Jan 28 22:12:15 volumio volumio[768]: info: CorePlayQueue::getTrack 0
Jan 28 22:12:15 volumio volumio[768]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
Jan 28 22:12:15 volumio volumio[768]: info: CoreCommandRouter::volumioPushState
Jan 28 22:12:15 volumio volumio[768]: info: CoreStateMachine::pushState
Jan 28 22:12:15 volumio volumio[768]: info: CorePlayQueue::getTrack 0
Jan 28 22:12:15 volumio volumio[768]: info: CoreCommandRouter::volumioPushState
Jan 28 22:12:15 volumio volumio[768]: info: ------------------------------ 122ms
Jan 28 22:12:15 volumio volumio[768]: info: ------------------------------ 121ms
Jan 28 22:12:15 volumio volumio[768]: info: [LastFM] Current track has sufficient metadata: title (Intended Simply) and artist (PKNN) passed on explicitly
Jan 28 22:12:15 volumio volumio[768]: |||||||||||||||||||||||| WARNING: FATAL ERROR |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Jan 28 22:12:15 volumio volumio[768]: TypeError: Cannot read property 'getTrackInfo' of null
Jan 28 22:12:15 volumio volumio[768]:     at ControllerLastFM.updateNowPlaying (/data/plugins/user_interface/lastfm/index.js:978:18)
Jan 28 22:12:15 volumio volumio[768]:     at ControllerLastFM.checkStateUpdate (/data/plugins/user_interface/lastfm/index.js:816:26)
Jan 28 22:12:15 volumio volumio[768]:     at Socket.<anonymous> (/data/plugins/user_interface/lastfm/index.js:110:52)
Jan 28 22:12:15 volumio volumio[768]:     at Socket.Emitter.emit (/data/plugins/user_interface/lastfm/node_modules/component-emitter/index.js:133:20)
Jan 28 22:12:15 volumio volumio[768]:     at Socket.onevent (/data/plugins/user_interface/lastfm/node_modules/socket.io-client/lib/socket.js:270:10)
Jan 28 22:12:15 volumio volumio[768]:     at Socket.onpacket (/data/plugins/user_interface/lastfm/node_modules/socket.io-client/lib/socket.js:228:12)
Jan 28 22:12:15 volumio volumio[768]:     at Manager.<anonymous> (/data/plugins/user_interface/lastfm/node_modules/component-bind/index.js:21:15)
Jan 28 22:12:15 volumio volumio[768]:     at Manager.Emitter.emit (/data/plugins/user_interface/lastfm/node_modules/component-emitter/index.js:133:20)
Jan 28 22:12:15 volumio volumio[768]:     at Manager.ondecoded (/data/plugins/user_interface/lastfm/node_modules/socket.io-client/lib/manager.js:332:8)
Jan 28 22:12:15 volumio volumio[768]:     at Decoder.<anonymous> (/data/plugins/user_interface/lastfm/node_modules/component-bind/index.js:21:15)
Jan 28 22:12:15 volumio volumio[768]:     at Decoder.Emitter.emit (/data/plugins/user_interface/lastfm/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
Jan 28 22:12:15 volumio volumio[768]:     at Decoder.add (/data/plugins/user_interface/lastfm/node_modules/socket.io-parser/index.js:246:12)
Jan 28 22:12:15 volumio volumio[768]:     at Manager.ondata (/data/plugins/user_interface/lastfm/node_modules/socket.io-client/lib/manager.js:322:16)
Jan 28 22:12:15 volumio volumio[768]:     at Socket.<anonymous> (/data/plugins/user_interface/lastfm/node_modules/component-bind/index.js:21:15)
Jan 28 22:12:15 volumio volumio[768]:     at Socket.Emitter.emit (/data/plugins/user_interface/lastfm/node_modules/component-emitter/index.js:133:20)
Jan 28 22:12:15 volumio volumio[768]:     at Socket.onPacket (/data/plugins/user_interface/lastfm/node_modules/engine.io-client/lib/socket.js:451:14)
Jan 28 22:12:15 volumio volumio[768]: |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Jan 28 22:12:16 volumio sudo[2345]:  volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/journalctl --since=2022-01-28 22:11
Jan 28 22:12:16 volumio sudo[2345]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jan 28 22:12:16 volumio sudo[2345]: pam_unix(sudo:session): session closed for user root
Jan 28 22:12:17 volumio volumio-remote-updater[489]: [2022-01-28 22:12:17] [error] handle_read_frame error: websocketpp.transport:7 (End of File)
Jan 28 22:12:17 volumio systemd[1]: volumio.service: Main process exited, code=exited, status=1/FAILURE
Jan 28 22:12:17 volumio systemd[1]: volumio.service: Failed with result 'exit-code'.
Jan 28 22:12:17 volumio volumio-remote-updater[489]: [2022-01-28 22:12:17] [disconnect] Disconnect close local:[1006,End of File] remote:[1006]
Jan 28 22:12:17 volumio systemd[1]: Started dynamicswap service.
Jan 28 22:12:17 volumio systemd[1]: dynamicswap.service: Succeeded.
Jan 28 22:12:17 volumio systemd[1]: volumio.service: Service RestartSec=100ms expired, scheduling restart.
Jan 28 22:12:17 volumio systemd[1]: volumio.service: Scheduled restart job, restart counter is at 1.
Jan 28 22:12:17 volumio systemd[1]: Stopped Volumio Backend Module.
Jan 28 22:12:17 volumio systemd[1]: Started Volumio Backend Module.
Jan 28 22:12:17 volumio systemd[1]: Started dynamicswap service.
Jan 28 22:12:17 volumio systemd[1]: dynamicswap.service: Succeeded.
Jan 28 22:12:19 volumio volumio[2358]: info: -------------------------------------------
Jan 28 22:12:19 volumio volumio[2358]: info: -----            Volumio3              ----
Jan 28 22:12:19 volumio volumio[2358]: info: -------------------------------------------
Jan 28 22:12:19 volumio volumio[2358]: info: -----          System startup          ----
Jan 28 22:12:19 volumio volumio[2358]: info: -------------------------------------------
Jan 28 22:12:20 volumio volumio[2358]: info: MYVOLUMIO Environment detected
Jan 28 22:12:21 volumio volumio[2358]: info: Plugin folders cleanup
Jan 28 22:12:21 volumio volumio[2358]: info: Scanning into folder /volumio/app/plugins/
Jan 28 22:12:21 volumio volumio[2358]: info: Scanning category audio_interface
Jan 28 22:12:21 volumio volumio[2358]: info: Scanning category miscellanea
Jan 28 22:12:21 volumio volumio[2358]: info: Scanning category music_service
Jan 28 22:12:21 volumio volumio[2358]: info: Scanning category plugins.json
Jan 28 22:12:21 volumio volumio[2358]: info: Scanning category system_controller
Jan 28 22:12:21 volumio volumio[2358]: info: Scanning category user_interface
Jan 28 22:12:21 volumio volumio[2358]: info: Scanning into folder /data/plugins/
Jan 28 22:12:21 volumio volumio[2358]: info: Scanning category miscellanea
Jan 28 22:12:21 volumio volumio[2358]: info: Scanning category user_interface
Jan 28 22:12:21 volumio volumio[2358]: info: Plugin folders cleanup completed
Jan 28 22:12:21 volumio volumio[2358]: info: -------------------------------------------
Jan 28 22:12:21 volumio volumio[2358]: info: -----      Core plugins startup        ----
Jan 28 22:12:21 volumio volumio[2358]: info: -------------------------------------------
Jan 28 22:12:21 volumio volumio[2358]: info: Loading plugins from folder /volumio/app/plugins/
Jan 28 22:12:21 volumio volumio[2358]: info: Adding plugin upnp to MyMusic Plugins
Jan 28 22:12:21 volumio volumio[2358]: info: Adding plugin airplay_emulation to MyMusic Plugins
Jan 28 22:12:21 volumio volumio[2358]: info: Adding plugin upnp_browser to MyMusic Plugins
Jan 28 22:12:21 volumio volumio[2358]: info: Loading plugins from folder /data/plugins/
Jan 28 22:12:21 volumio volumio[2358]: info: Loading plugin "system"...
Jan 28 22:12:21 volumio volumio[2358]: info: Loading plugin "appearance"...
```

Again, I'm not an expert but it seems as if the last.fm plugin throws a fatal error which causes Volumio to restart.

3. LastFM link in sidebar of webUI
When I click on 'LastFM' in the sidebar of the webUI, a loading bar moves across the top, and nothing else happens. Here's the log output:
```
Jan 28 23:28:19 volumio sudo[3584]:  volumio : TTY=pts/0 ; PWD=/data ; USER=root ; COMMAND=/bin/journalctl -f
Jan 28 23:28:19 volumio sudo[3584]: pam_unix(sudo:session): session opened for user root by volumio(uid=0)
Jan 28 23:28:24 volumio volumio[3355]: info: CoreCommandRouter::executeOnPlugin: lastfm , handleBrowseUri
Jan 28 23:28:24 volumio volumio[3355]: error: Failed to execute browseSource: TypeError: Cannot read property 'then' of undefined
```

**Comment by Saiyato** [comment]
That doesn't look good indeed. What platform are you using (x86 or pi) and what exact version of Volumio?

In the meantime I will try to reproduce.

**Comment by Saiyato** [comment]
Update: testing right now.

Setup:
- Raspberry Pi 2B
- Volumio 3.179

**Comment by Saiyato** [comment]
Plugin start & opening settings page logs:
```
Jan 29 09:46:10 volumiotest volumio[616]: info: Enabling plugin lastfm
Jan 29 09:46:10 volumiotest volumio[616]: info: Loading plugin "lastfm"...
Jan 29 09:46:10 volumiotest volumio[616]: info: PLUGIN START: lastfm
Jan 29 09:46:10 volumiotest volumio[616]: info: CoreCommandRouter::volumioAddToBrowseSources[object Object]
Jan 29 09:46:10 volumiotest volumio[616]: info: [1643449570063] CoreMusicLibrary::Adding element LastFM
Jan 29 09:46:10 volumiotest volumio[616]: info: CoreCommandRouter::executeOnPlugin: my_music , getDisabledSources
Jan 29 09:46:10 volumiotest volumio[616]: Cannot find translation for sourceMedia Servers
Jan 29 09:46:10 volumiotest volumio[616]: Cannot find translation for sourceLastFM
Jan 29 09:46:10 volumiotest volumio[616]: info: [LastFM] scrobbler initiated!
Jan 29 09:46:10 volumiotest volumio[616]: info: [LastFM] extended logging: false
Jan 29 09:46:10 volumiotest volumio[616]: info: [LastFM] try scrobble stream/radio plays: true
Jan 29 09:46:10 volumiotest volumio[616]: info: [LastFM] Configuration parameters missing:  "API_KEY"  "API_SECRET"  "username"  "authToken"
Jan 29 09:46:10 volumiotest volumio[616]: info: [LastFM] Left init routine
Jan 29 09:46:10 volumiotest volumio[616]: info: [LastFM] Socket already connected: true
Jan 29 09:46:10 volumiotest volumio[616]: info: [LastFM] finished init with error: Configuration parameters missing:  "API_KEY"  "API_SECRET"  "username"  "authToken"
Jan 29 09:46:10 volumiotest volumio[616]: info: Done.
Jan 29 09:46:15 volumiotest volumio[616]: info: CoreCommandRouter::getUIConfigOnPlugin
Jan 29 09:46:15 volumiotest volumio[616]: info: Loaded the previous config.
Jan 29 09:46:15 volumiotest volumio[616]: info: ## populating UI...
Jan 29 09:46:15 volumiotest volumio[616]: info: 1/3 settings loaded
Jan 29 09:46:15 volumiotest volumio[616]: info: 2/3 settings loaded
Jan 29 09:46:15 volumiotest volumio[616]: info: 3/3 settings loaded
Jan 29 09:46:15 volumiotest volumio[616]: info: Populated config screen.
Jan 29 09:46:19 volumiotest systemd[1]: Starting Cleanup of Temporary Directories...
Jan 29 09:46:19 volumiotest volumio[616]: ------------------------------------ BT MESSAGE: BT STATUS: running
Jan 29 09:46:19 volumiotest volumio[616]: BT PLUGIN MESSAGE: Playing: false
Jan 29 09:46:19 volumiotest volumio[616]: BT PLUGIN MESSAGE: VOLATILE: undefined
Jan 29 09:46:19 volumiotest volumio[616]: BT PLUGIN MESSAGE: STATE:undefined
Jan 29 09:46:19 volumiotest systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
Jan 29 09:46:19 volumiotest systemd[1]: Started Cleanup of Temporary Directories.

```

**Comment by Saiyato** [comment]
Found the problem! Your credentials aren't working, I just used the plugin without setting my credentials + API settings. I got the exact same items, I will patch this (shouldn't fatally fail):

```
Jan 29 09:50:09 volumiotest volumio[616]: info: [LastFM] Current track has sufficient metadata: title (Another Day In Paradise) and artist (Phil Collins) passed on explicitly
Jan 29 09:50:09 volumiotest volumio[616]: |||||||||||||||||||||||| WARNING: FATAL ERROR |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Jan 29 09:50:09 volumiotest volumio[616]: TypeError: Cannot read property 'getTrackInfo' of null
Jan 29 09:50:09 volumiotest volumio[616]:     at ControllerLastFM.updateNowPlaying (/data/plugins/user_interface/lastfm/index.js:978:18)
Jan 29 09:50:09 volumiotest volumio[616]:     at ControllerLastFM.checkStateUpdate (/data/plugins/user_interface/lastfm/index.js:816:26)
Jan 29 09:50:09 volumiotest volumio[616]:     at Socket.<anonymous> (/data/plugins/user_interface/lastfm/index.js:110:52)
Jan 29 09:50:09 volumiotest volumio[616]:     at Socket.Emitter.emit (/data/plugins/user_interface/lastfm/node_modules/component-emitter/index.js:133:20)
Jan 29 09:50:09 volumiotest volumio[616]:     at Socket.onevent (/data/plugins/user_interface/lastfm/node_modules/socket.io-client/lib/socket.js:270:10)
Jan 29 09:50:09 volumiotest volumio[616]:     at Socket.onpacket (/data/plugins/user_interface/lastfm/node_modules/socket.io-client/lib/socket.js:228:12)
Jan 29 09:50:09 volumiotest volumio[616]:     at Manager.<anonymous> (/data/plugins/user_interface/lastfm/node_modules/component-bind/index.js:21:15)
Jan 29 09:50:09 volumiotest volumio[616]:     at Manager.Emitter.emit (/data/plugins/user_interface/lastfm/node_modules/component-emitter/index.js:133:20)
Jan 29 09:50:09 volumiotest volumio[616]:     at Manager.ondecoded (/data/plugins/user_interface/lastfm/node_modules/socket.io-client/lib/manager.js:332:8)
Jan 29 09:50:09 volumiotest volumio[616]:     at Decoder.<anonymous> (/data/plugins/user_interface/lastfm/node_modules/component-bind/index.js:21:15)
Jan 29 09:50:09 volumiotest volumio[616]:     at Decoder.Emitter.emit (/data/plugins/user_interface/lastfm/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
Jan 29 09:50:09 volumiotest volumio[616]:     at Decoder.add (/data/plugins/user_interface/lastfm/node_modules/socket.io-parser/index.js:246:12)
Jan 29 09:50:09 volumiotest volumio[616]:     at Manager.ondata (/data/plugins/user_interface/lastfm/node_modules/socket.io-client/lib/manager.js:322:16)
Jan 29 09:50:09 volumiotest volumio[616]:     at Socket.<anonymous> (/data/plugins/user_interface/lastfm/node_modules/component-bind/index.js:21:15)
Jan 29 09:50:09 volumiotest volumio[616]:     at Socket.Emitter.emit (/data/plugins/user_interface/lastfm/node_modules/component-emitter/index.js:133:20)
Jan 29 09:50:09 volumiotest volumio[616]:     at Socket.onPacket (/data/plugins/user_interface/lastfm/node_modules/engine.io-client/lib/socket.js:451:14)
Jan 29 09:50:09 volumiotest volumio[616]: |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
```

**Comment by Saiyato** [comment]
Found bug two as well, saving credentials is giving me headaches now too :wink:

**Comment by Saiyato** [comment]
Fix available, will update in a bit!
